#!/usr/bin/env bash
#
# Idempotent setup for the DentaFlow OS local development environment.
#
#   1. Installs root Node dependencies.
#   2. Generates Temara_Dashboard/.env.local with LOCAL-ONLY dev credentials
#      (random JWT secret + scrypt password hashes) when it does not exist.
#
# The generated .env.local is git-ignored and contains development-only test
# credentials — never production secrets. External integrations (n8n, Redis,
# Baserow, Twilio, Cal.com) require real secrets and are not exercised locally.
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

echo "==> Installing root Node dependencies (npm install)"
npm install --no-audit --no-fund

DASH_DIR="$REPO_ROOT/Temara_Dashboard"
ENV_FILE="$DASH_DIR/.env.local"

# Local-only development credentials (safe to display; not production secrets).
DEV_DOCTOR_USERNAME="docteur"
DEV_DOCTOR_PASSWORD="dentaflow"
DEV_ASSISTANT_USERNAME="assistante"
DEV_ASSISTANT_PASSWORD="dentaflow"

if [ -f "$ENV_FILE" ]; then
  echo "==> $ENV_FILE already exists — leaving it untouched (idempotent)."
else
  echo "==> Generating $ENV_FILE with local dev credentials"
  cd "$DASH_DIR"

  JWT_SECRET="$(node -e "console.log(require('crypto').randomBytes(48).toString('hex'))")"
  DOCTOR_HASH="$(node -e "console.log(require('./api/_lib/auth-crypto').hashPassword(process.argv[1]))" "$DEV_DOCTOR_PASSWORD")"
  ASSISTANT_HASH="$(node -e "console.log(require('./api/_lib/auth-crypto').hashPassword(process.argv[1]))" "$DEV_ASSISTANT_PASSWORD")"

  cat > "$ENV_FILE" <<EOF
# LOCAL DEVELOPMENT ONLY — generated by scripts/setup-dev-env.sh
# Do NOT use these values in production. This file is git-ignored.
#
# Dev login credentials:
#   Médecin      -> ${DEV_DOCTOR_USERNAME} / ${DEV_DOCTOR_PASSWORD}
#   Assistant(e) -> ${DEV_ASSISTANT_USERNAME} / ${DEV_ASSISTANT_PASSWORD}

JWT_SECRET=${JWT_SECRET}

DOCTOR_USERNAME=${DEV_DOCTOR_USERNAME}
DOCTOR_PASSWORD_HASH=${DOCTOR_HASH}

ASSISTANT_USERNAME=${DEV_ASSISTANT_USERNAME}
ASSISTANT_PASSWORD_HASH=${ASSISTANT_HASH}

# CORS origin for /api/* (local dev). Leave blank to allow same-origin requests.
VERCEL_FRONTEND_URL=

# Direct PostgreSQL for Wave 1 operational APIs (roster, waitlist, KPIs, status).
DATABASE_URL=postgres://dentaflow:dentaflow@127.0.0.1:5432/dentaflow
CLINIC_ID=temara

# External integrations are intentionally left unset for local dev.
# Populate these to exercise remaining n8n/Redis-backed proxy endpoints:
#   N8N_AUTH_KEY, N8N_WEBHOOK_FILL_GAP, N8N_WEBHOOK_BULK_SMS, ...
#   REDIS_CONNECTION_URL, REDIS_REST_TOKEN
EOF

  cd "$REPO_ROOT"
fi

echo "==> Setup complete."
echo "    Start the dev server with: node scripts/dev-server.js"
echo "    Then open http://localhost:3000"
